test_that("format helpers produce stable display strings", {
  expect_identical(format_cor(0.1234), "0.123")
  expect_identical(format_cor(NA_real_), "NA")
  expect_identical(format_rate(0.125), "12.50%")
  expect_identical(format_rate(NA_real_), "NA")
  expect_identical(format_threshold_level(0.005), "0.005")
  expect_identical(format_threshold_level(0.2), "0.2")
  expect_identical(format_yes_no(TRUE), "yes")
  expect_identical(format_yes_no(FALSE), "no")
  expect_identical(format_covariates(TRUE), "included")
  expect_identical(format_covariates(FALSE), "none")
  expect_identical(edge_storage_label("none"), "not stored")
  expect_identical(edge_storage_label("sum"), "summed across folds")
  expect_identical(edge_storage_label("all"), "stored for each fold")
})

test_that("prediction labels use full names", {
  expect_identical(prediction_label("both"), "Combined")
  expect_identical(prediction_label("pos"), "Positive")
  expect_identical(prediction_label("neg"), "Negative")
})
