test_that("Works for basic summary", {
  withr::local_seed(123)
  conmat <- matrix(rnorm(100), ncol = 10)
  behav <- rnorm(10)
  summary_result <- summary(cpm(conmat, behav))
  expect_s3_class(summary_result, "cpm_summary")
  expect_snapshot(summary_result)
  summary_result <- summary(cpm(conmat, behav, return_edges = "sum"))
  expect_s3_class(summary_result, "cpm_summary")
  expect_snapshot(summary_result)
  summary_result <- summary(cpm(conmat, behav, return_edges = "all"))
  expect_s3_class(summary_result, "cpm_summary")
  expect_snapshot(summary_result)
})
